### PR TITLE
Cleanup MacOS section

### PR DESCRIPTION
**Pull request by wormeyman**
Hey all I just got the macOS version setup and it was super confusing so I simplified things let me know if you still want to keep some of the previous instructions.

### CODE REVIEW

**Review by ChristopherHX — CHANGES_REQUESTED** [review]
You cannot partially remove the previous version section,
- build from source sections are outdated and refer to an old version
- Linux mint, ubuntu 19.04 etc are the previous version too

Either remove it completly or keep it as it is.

**Comment by wormeyman** [comment]
1. Hi, i thought i did completely remove the previous version section.
1. build from source sections are outdated and refer to an old version
	1. Is this a reference to MacOS or the linux? 
1. I am not sure what you mean by "Linux mint, ubuntu 19.04 etc are the previous version too"

**Comment by ChristopherHX** [comment]
> Hi, i thought i did completely remove the previous version section.

But it isn't, I think you haven't understood that everything after Previous version is old content. I can remove this section myself, but your PR would break the whole layout.

Please compare the rendered Getting started page of your PR. Nested headlines.

I mean this isn't like it should be, there was no linux in the macOS section before.
Screenshot_20210709-194642

## With this pr:
### h1 macos 
text
#### h2 Linux mint (no thats not macos)
#### h2 ubuntu 19.04 (no thats not macos)
## Before
### h1 macos 
text
### h1 previous version
#### h2 macos
old version of macos + source build
#### h2 Linux mint
#### h2 ubuntu 19.04

**Comment by wormeyman** [comment]
I did not understand that all of that was previous version, thank you. I have removed all of it and made source build a subsection

**Review by ChristopherHX — APPROVED** [review]

**Comment by ChristopherHX** [comment]
Looks fine now.
I have had the feeling not only you still scrolled down to the previous version section.

**Pull request merged**
